### ISSUE TITLE
Not possible to login

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/AthenaUI#166]
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request [GET /cas/idp/profile/SAML2/Redirect/SSO](https://cas.odysseusinc.com/cas/idp/profile/SAML2/Redirect/SSO).

Reason: Error reading from remote server

**Comment by konstjar** [comment]
Thank you for reporting. The issue was resolved.
