### ISSUE TITLE
Search position is reset when going back from concept page 

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/AthenaUI#56]
**Steps to reproduce:**

Do some search with a lot of results
Click on any page except 1st
Scroll down to the middle of the page
Click on some concept
Click back button on concept page

**Result:**
You are again on 1st page of search results

**Expected result:**
Search position (page and ideally scroll position) is saved when going back from concept page

**Comment by acumarav** [comment]
Keeping scroll position extracted to separate ticket: https://github.com/OHDSI/ArachneUI/issues/741
