### ISSUE TITLE
No data available if choose second time the same value in show by drop-down

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/AthenaUI#57]
**Steps to reproduce:**
Do some search with a lot of results
Click on 50 in show by drop-down
Click again on 50 in show by drop-down

**Result:**
After second click you will have "No data available"
If second time choose another option (ex. 30) works ok

**Expected result:**
You still get your search result

**Comment by acumarav** [comment]
Cause by the weird behavior of underlying library
